school_project/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('info.urls'))
]

school_project/info/urls.py
from django.urls import path

from . import views

app_name = 'info'
urlpatterns = [
    path('', views.list_of_schools, name="list_of_schools"),
    path('school/<int:school_id>/', views.school_details, name="school_details"),
    path('student/', views.list_of_students, name="list_of_students"),
    path('student/<int:student_id>/', views.student_details, name="student_details"),
]

school_project/info/models.py
from django.db import models

__all__ = (
    'School',
    'Students',
)


class School(models.Model):
    school_name = models.CharField(max_length=16)

    def __str__(self):
        return self.school_name


class Students(models.Model):
    student_school_name = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
    )
    student_name = models.CharField(max_length=10)
    friend_name_list = models.ManyToManyField('self')

    def __str__(self):
        # 이한영 (친구: a, b, c)
        #  QuerySet순회 및 문자열 포매팅
        friend_list = self.friend_name_list.all()
        friend_list_str = ', '.join([friend.student_name for friend in friend_list])
        return f'{self.student_name} (친구: {friend_list_str})'

school_project/info/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.template.loader import get_template

from .models import School, Students


def list_of_schools(request):
    '''
    모든 학교 목록을 출력.
    학교 상세보기 링크 구현
    :param request:
    :return:
    '''
    school_list = School.objects.all()

    template = get_template('info/info_of_schools.html')
    context = {'list_of_schools': school_list}
    return HttpResponse(template.render(context, request))


def school_details(request, school_id):
    '''
    학교 상세보기
        URL 이름으로 school_id를 사용, 해당 학교 출력.
        속하는 모든 학생 목록을 보여줌.
        학생 상세보기 링크 구현
    :param:
    :return:
    '''
    print(school_id)
    try:
        school_id_details = School.objects.get(pk=school_id)
        students_in_school =  Students.objects.filter(student_school_name__pk=school_id)
    except School.DoesNotExist:
        raise Http404('그런건 없다.')
    else:
        # school_detail = School.objects.get(id=School.school_name)

        template = get_template('info/school_details.html')
        context = {
            # 'school_detail': school_detail,
            'school_id_details': school_id_details,
            'students_in_school': students_in_school,
        }
        return HttpResponse(template.render(context, request))


def list_of_students(request):
    student_list = Students.objects.all()

    template = get_template('info/list_of_students.html')

    context = {'list_of_students': student_list}
    return HttpResponse(template.render(context, request))


def student_details(request, student_id):
    try:
        student_id_details = Students.objects.get(pk=student_id)
    except Students.DoesNotExist:
        raise Http404('그런건 없다.')
    else:
        template = get_template('info/student_details.html')
        context = {
            'student_id_details': student_id_details,
        }
        return HttpResponse(template.render(context, request))

templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/info/info_of_schools.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>List of schools</h1>

{% if list_of_schools %}
    <ul>
    {% for school in list_of_schools %}
        <li><a href="{% url 'info:school_details' school.id %}">{{ school.school_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No schools in database.</p>
{% endif %}


</body>
</html>

templates/info/list_of_students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1> List of students</h1>

{% if list_of_students %}
    <ul>
    {% for student in list_of_students %}
        {% url 'info:student_details' student.id as link_to_list %}
        {% if link_to_list %}
        <li><a href="{{ link_to_list }}">{{ student.student_name }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No students in database.</p>
{% endif %}
</body>
</html>

templates/info/school_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if school_id_details %}
    <p>{{ school_id_details }}의 정보</p>
    {% for student in students_in_school %}
        <p><a href="{% url 'info:student_details' student.id %}">{{ student.student_name }}</a></p>
    {% endfor %}
    {{ school_id_details }}
    끗
{% else %}
    <p>No schools in database.</p>
{% endif %}

</body>
</html>

templates/info/student_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% if student_id_details %}
        <p>특정 학생의 정보</p>
        {{ student_id_details }}
{#        {% for student_data in student_id_details %}#}
{#            {{ student_data }}#}
{#        {% endfor %}#}
    {% else %}
        <p>No students in database.</p>
    {% endif %}

</body>
</html>